WhatsForDinner/Controllers/CalendarsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WhatsForDinner.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;
using System;
using System.Data;
namespace WhatsForDinner.Controllers
{
  [Authorize]

  public class CalendarsController : Controller
  {
    private readonly WhatsForDinnerContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public CalendarsController(UserManager<ApplicationUser> userManager, WhatsForDinnerContext db)
    {
      _userManager = userManager;
      _db = db;
    }

      public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userCalendars = _db.RecipeWeeks.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userCalendars);
    }

    public ActionResult Create()
    {
      return View();
    }
    public async Task<ActionResult> CreateAll()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipes = _db.Recipes.Where(entry=> entry.User.Id==currentUser.Id).ToList();
      List<Recipe> UserBreakfast = new List<Recipe>{};
      List<Recipe> UserLunch = new List<Recipe>{};
      List<Recipe> UserDinner = new List<Recipe>{};
      foreach(Recipe recipe in userRecipes){
        if(recipe.isBreakfast){
          UserBreakfast.Add(recipe);
        }
        else if(recipe.isLunch){
          UserLunch.Add(recipe);
        }
        else{
          UserDinner.Add(recipe);
        }
      }
      if(userRecipes.Count == 0){
        return View(userRecipes);
      }
      else
      {
        List<Recipe> WeekBreakfast = Recipe.RandomBreakfasts(UserBreakfast);
        List<Recipe> WeekLunch = Recipe.RandomLunches(UserLunch);
        List<Recipe> WeekDinner = Recipe.RandomDinners(UserDinner);
        List<Recipe> WeeklyRecipes = Recipe.GetWeekPlan(WeekBreakfast, WeekLunch, WeekDinner);
        return View(WeeklyRecipes);
      }
    }

    [HttpPost]
    public async Task<ActionResult> CreateAll(List<Recipe> WeeklyRecipes)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      RecipeDay RecipeMonday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[0].RecipeId, LunchRecipeId = WeeklyRecipes[7].RecipeId, DinnerRecipeId = WeeklyRecipes[14].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeMonday);
      RecipeDay RecipeTuesday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[1].RecipeId, LunchRecipeId = WeeklyRecipes[8].RecipeId, DinnerRecipeId = WeeklyRecipes[15].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeTuesday);
      RecipeDay RecipeWednesday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[2].RecipeId, LunchRecipeId = WeeklyRecipes[9].RecipeId, DinnerRecipeId = WeeklyRecipes[16].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeWednesday);
      RecipeDay RecipeThursday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[3].RecipeId, LunchRecipeId = WeeklyRecipes[10].RecipeId, DinnerRecipeId = WeeklyRecipes[17].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeThursday);
      RecipeDay RecipeFriday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[4].RecipeId, LunchRecipeId = WeeklyRecipes[11].RecipeId, DinnerRecipeId = WeeklyRecipes[18].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeFriday);
      RecipeDay RecipeSaturday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[5].RecipeId, LunchRecipeId = WeeklyRecipes[12].RecipeId, DinnerRecipeId = WeeklyRecipes[19].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeSaturday);
      RecipeDay RecipeSunday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[6].RecipeId, LunchRecipeId = WeeklyRecipes[13].RecipeId, DinnerRecipeId = WeeklyRecipes[20].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeSunday);
      DateTime weekDate = DateTime.Now;
      RecipeWeek thisWeek = new RecipeWeek() { Week = new List<RecipeDay> { RecipeMonday, RecipeTuesday, RecipeWednesday, RecipeThursday, RecipeFriday, RecipeSaturday, RecipeSunday }, ApplicationUserId = currentUser.Id, EverythingPlan = true};
      if(weekDate.DayOfWeek == DayOfWeek.Monday){
        thisWeek.WeekOf = weekDate;
      }
      else if(weekDate.DayOfWeek != DayOfWeek.Monday){
        if(weekDate.DayOfWeek == DayOfWeek.Tuesday)
        {thisWeek.WeekOf = weekDate.AddDays(6);}
        else if(weekDate.DayOfWeek == DayOfWeek.Wednesday)
        {thisWeek.WeekOf = weekDate.AddDays(5);}
        else if(weekDate.DayOfWeek == DayOfWeek.Thursday)
        {thisWeek.WeekOf = weekDate.AddDays(4);}
        else if(weekDate.DayOfWeek == DayOfWeek.Friday)
        {thisWeek.WeekOf = weekDate.AddDays(3);}
        else if(weekDate.DayOfWeek == DayOfWeek.Saturday)
        {thisWeek.WeekOf = weekDate.AddDays(2);}
        else
        {thisWeek.WeekOf = weekDate.AddDays(1);}
      }
      _db.RecipeWeeks.Add(thisWeek);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> CreateBreakfast()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipes = _db.Recipes.Where(entry=> entry.User.Id==currentUser.Id).ToList();
      List<Recipe> UserBreakfast = new List<Recipe>{};
      // List<Recipe> UserLunch = new List<Recipe>{};
      // List<Recipe> UserDinner = new List<Recipe>{};
      foreach(Recipe recipe in userRecipes){
        if(recipe.isBreakfast){
          UserBreakfast.Add(recipe);
        }
      }
      if(userRecipes.Count == 0){
        return View(userRecipes);
      }
      else
      {
        List<Recipe> WeeklyRecipes = Recipe.RandomBreakfasts(UserBreakfast);
        return View(WeeklyRecipes);
      }
    }

[HttpPost]
    public async Task<ActionResult> CreateBreakfast(List<Recipe> WeeklyRecipes)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      RecipeDay RecipeMonday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[0].RecipeId, LunchRecipeId = WeeklyRecipes[0].RecipeId, DinnerRecipeId = WeeklyRecipes[0].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeMonday);
      RecipeDay RecipeTuesday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[1].RecipeId, LunchRecipeId = WeeklyRecipes[1].RecipeId, DinnerRecipeId = WeeklyRecipes[1].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeTuesday);
      RecipeDay RecipeWednesday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[2].RecipeId, LunchRecipeId = WeeklyRecipes[2].RecipeId, DinnerRecipeId = WeeklyRecipes[2].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeWednesday);
      RecipeDay RecipeThursday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[3].RecipeId, LunchRecipeId = WeeklyRecipes[3].RecipeId, DinnerRecipeId = WeeklyRecipes[3].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeThursday);
      RecipeDay RecipeFriday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[4].RecipeId, LunchRecipeId = WeeklyRecipes[4].RecipeId, DinnerRecipeId = WeeklyRecipes[4].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeFriday);
      RecipeDay RecipeSaturday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[5].RecipeId, LunchRecipeId = WeeklyRecipes[5].RecipeId, DinnerRecipeId = WeeklyRecipes[5].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeSaturday);
      RecipeDay RecipeSunday = new RecipeDay(){BreakfastRecipeId = WeeklyRecipes[6].RecipeId, LunchRecipeId = WeeklyRecipes[6].RecipeId, DinnerRecipeId = WeeklyRecipes[6].RecipeId, User = currentUser};
      _db.RecipeDays.Add(RecipeSunday);
      DateTime weekDate = DateTime.Now;
      RecipeWeek thisWeek = new RecipeWeek() { Week = new List<RecipeDay> { RecipeMonday, RecipeTuesday, RecipeWednesday, RecipeThursday, RecipeFriday, RecipeSaturday, RecipeSunday }, ApplicationUserId = currentUser.Id, BreakfastPlan = true};
      if(weekDate.DayOfWeek == DayOfWeek.Monday){
        thisWeek.WeekOf = weekDate;
      }
      else if(weekDate.DayOfWeek != DayOfWeek.Monday){
        if(weekDate.DayOfWeek == DayOfWeek.Tuesday)
        {thisWeek.WeekOf = weekDate.AddDays(6);}
        else if(weekDate.DayOfWeek == DayOfWeek.Wednesday)
        {thisWeek.WeekOf = weekDate.AddDays(5);}
        else if(weekDate.DayOfWeek == DayOfWeek.Thursday)
        {thisWeek.WeekOf = weekDate.AddDays(4);}
        else if(weekDate.DayOfWeek == DayOfWeek.Friday)
        {thisWeek.WeekOf = weekDate.AddDays(3);}
        else if(weekDate.DayOfWeek == DayOfWeek.Saturday)
        {thisWeek.WeekOf = weekDate.AddDays(2);}
        else
        {thisWeek.WeekOf = weekDate.AddDays(1);}
      }
      _db.RecipeWeeks.Add(thisWeek);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
      public async Task<ActionResult> CreateLunch()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipes = _db.Recipes.Where(entry=> entry.User.Id==currentUser.Id).ToList();
      List<Recipe> UserLunch = new List<Recipe>{};

      foreach(Recipe recipe in userRecipes){
        if(recipe.isLunch){
          UserLunch.Add(recipe);
        }
      }
      if(userRecipes.Count == 0){
        return View(userRecipes);
      }
      else
      {
        List<Recipe> WeeklyRecipes = Recipe.RandomLunches(UserLunch);
        return View(WeeklyRecipes);
      }
    }

[HttpPost]

WhatsForDinner/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using WhatsForDinner.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;
using System;

namespace WhatsForDinner.Controllers
{
  [Authorize]
  public class RecipesController : Controller
  {
    private readonly WhatsForDinnerContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public RecipesController(UserManager<ApplicationUser> userManager, WhatsForDinnerContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userRecipes = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userRecipes);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      recipe.User = currentUser;
      _db.Recipes.Add(recipe);
      if(recipe.isBreakfast){
        _db.BreakfastRecipes.Add(new BreakfastRecipe(){Recipe = recipe});
      }
      else if(recipe.isLunch){
        _db.LunchRecipes.Add(new LunchRecipe(){Recipe = recipe});
      }
      else{
        _db.DinnerRecipes.Add(new DinnerRecipe(){Recipe = recipe});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Import()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Import(ImportedRecipe importedRecipe)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      importedRecipe.User = currentUser;
      var thisRecipe = ImportedRecipe.GetRecipe(EnvironmentVariables.apiKey, importedRecipe.sourceUrl);
      ImportedRecipe newRecipe = new ImportedRecipe(){title = thisRecipe.title, sourceUrl = thisRecipe.sourceUrl,image = thisRecipe.image, User = currentUser, Breakfast = importedRecipe.Breakfast, Lunch = importedRecipe.Lunch, Dinner = importedRecipe.Dinner, MinFrequency = importedRecipe.MinFrequency};
      _db.ImportedRecipes.Add(newRecipe);
      Recipe recipe = ImportedRecipe.ConvertToRecipe(newRecipe);
      _db.Recipes.Add(recipe);
      _db.SaveChanges();
      Console.WriteLine(thisRecipe.title);
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }
    public ActionResult Edit(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }
    [HttpPost]
    public ActionResult Edit(Recipe recipe)
    {
      _db.Entry(recipe).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      _db.Recipes.Remove(thisRecipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

WhatsForDinner/Views/Calendars/Create.cshtml
@{
  Layout = "_Layout";
}

<p>What meal would you like to create a plan for?</p>
<div class="clickable">@Html.ActionLink("Everything","CreateAll","Calendars" )</div>
<div class="clickable">@Html.ActionLink("Just Breakfast","CreateBreakfast","Calendars" )</div>
<div class="clickable">@Html.ActionLink("Just Lunch","CreateLunch","Calendars" )</div>
<div class="clickable">@Html.ActionLink("Just Dinners","CreateDinner","Calendars" )</div>

WhatsForDinner/Views/Calendars/CreateAll.cshtml
@{
  Layout = "_Layout";
}
@model List<WhatsForDinner.Models.Recipe>;
@if(Model.Count == 0 || Model.Count > 0 && Model.Count < 7){
<p>You don't have enough recipes in your collection for us to make meal plan for you, please add some to get started!</p>
}
else{
<div class="card-container">
@using(Html.BeginForm()){
  <div id="calender-card-container">
    <div class ="row">
      <div id="calendar-card" class="col">
        <h4 class="day">Monday</h4>
        <h4>Breakfast</h4>
        @Html.HiddenFor(m=>m[0].RecipeId)
        <p>@Html.TextBoxFor(m => m[0].Title, new { @readonly="readonly" })</p>
        <h4>Lunch</h4>
        @Html.HiddenFor(m=>m[7].RecipeId)
        <p>@Html.TextBoxFor(m => m[7].Title,  new { @readonly="readonly" })</p>
        <h4>Dinner</h4>
        @Html.HiddenFor(m=>m[14].RecipeId)
        <p>@Html.TextBoxFor(m => m[14].Title,  new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Tuesday</h4>
        <h4>Breakfast</h4>
        @Html.HiddenFor(m=>m[1].RecipeId)
        <p>@Html.TextBoxFor(m => m[1].Title, new { @readonly="readonly" })</p>
        <h4>Lunch</h4>
        @Html.HiddenFor(m=>m[8].RecipeId)
        <p>@Html.TextBoxFor(m => m[8].Title, new { @readonly="readonly" })</p>
        <h4>Dinner</h4>
        @Html.HiddenFor(m=>m[15].RecipeId)
        <p>@Html.TextBoxFor(m => m[15].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Wednesday</h4>
        <h4>Breakfast</h4>
        @Html.HiddenFor(m=>m[2].RecipeId)
        <p>@Html.TextBoxFor(m => m[2].Title, new { @readonly="readonly" })</p>
        <h4>Lunch</h4>
        @Html.HiddenFor(m=>m[9].RecipeId)
        <p>@Html.TextBoxFor(m => m[9].Title, new { @readonly="readonly" })</p>
        <h4>Dinner</h4>
        @Html.HiddenFor(m=>m[16].RecipeId)
        <p>@Html.TextBoxFor(m => m[16].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Thursday</h4>
        <h4>Breakfast</h4>
        @Html.HiddenFor(m=>m[3].RecipeId)
        <p>@Html.TextBoxFor(m => m[3].Title, new { @readonly="readonly" })</p>
        <h4>Lunch</h4>
        @Html.HiddenFor(m=>m[10].RecipeId)
        <p>@Html.TextBoxFor(m => m[10].Title, new { @readonly="readonly" })</p>
        <h4>Dinner</h4>
        @Html.HiddenFor(m=>m[17].RecipeId)
        <p>@Html.TextBoxFor(m => m[17].Title, new { @readonly="readonly" })</p>
      </div>
    </div>
    <div class="row">
      <div id="calendar-card" class="col">
          <h4 class="day">Friday</h4>
          <h4>Breakfast</h4>
          @Html.HiddenFor(m=>m[4].RecipeId)
          <p>@Html.TextBoxFor(m => m[4].Title, new { @readonly="readonly" })</p>
          <h4>Lunch</h4>
          @Html.HiddenFor(m=>m[11].RecipeId)
          <p>@Html.TextBoxFor(m => m[11].Title, new { @readonly="readonly" })</p>
          <h4>Dinner</h4>
          @Html.HiddenFor(m=>m[18].RecipeId)
          <p>@Html.TextBoxFor(m => m[18].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
          <h4 class="day">Saturday</h4>
          <h4>Breakfast</h4>
          @Html.HiddenFor(m=>m[5].RecipeId)
          <p>@Html.TextBoxFor(m => m[5].Title, new { @readonly="readonly" })</p>
          <h4>Lunch</h4>
          @Html.HiddenFor(m=>m[12].RecipeId)
          <p>@Html.TextBoxFor(m => m[12].Title, new { @readonly="readonly" })</p>
          <h4>Dinner</h4>
          @Html.HiddenFor(m=>m[19].RecipeId)
          <p>@Html.TextBoxFor(m => m[19].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Sunday</h4>
        <h4>Breakfast</h4>
        @Html.HiddenFor(m=>m[6].RecipeId)
        <p>@Html.TextBoxFor(m => m[6].Title, new { @readonly="readonly" })</p>
        <h4>Lunch</h4>
        @Html.HiddenFor(m=>m[13].RecipeId)
        <p>@Html.TextBoxFor(m => m[13].Title, new { @readonly="readonly" })</p>
        <h4>Dinner</h4>
        @Html.HiddenFor(m=>m[20].RecipeId)
        <p>@Html.TextBoxFor(m => m[20].Title, new { @readonly="readonly" })</p>
      </div>
      </div>
      </div>
      <div class="row">
      <div id="calendar-card" class ="col">
        <input type="submit" class="submit" value="Save Meal Plan"><br>
        <div onClick="window.location.reload();" class="clickable">Reshuffle</div> 
      </div>
    </div>
    <br>
  }
  </div>
}

WhatsForDinner/Views/Calendars/CreateBreakfast.cshtml
@{
  Layout = "_Layout";
}
@model List<WhatsForDinner.Models.Recipe>;
@if(Model.Count == 0 || Model.Count > 0 && Model.Count < 7){
<p>You don't have enough recipes in your collection for us to make meal plan for you, please add some to get started!</p>
}
else{
<div class="card-container">
@using(Html.BeginForm()){
    <div class ="row">
      <div id="calendar-card" class="col">
        <h4 class="day">Monday</h4>
        @Html.HiddenFor(m=>m[0].RecipeId)
        <p>@Html.TextBoxFor(m => m[0].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Tuesday</h4>
        @Html.HiddenFor(m=>m[1].RecipeId)
        <p>@Html.TextBoxFor(m => m[1].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Wednesday</h4>
        @Html.HiddenFor(m=>m[2].RecipeId)
        <p>@Html.TextBoxFor(m => m[2].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Thursday</h4>
        @Html.HiddenFor(m=>m[3].RecipeId)
        <p>@Html.TextBoxFor(m => m[3].Title, new { @readonly="readonly" })</p>
      </div>
    </div>
    <div class="row">
      <div id="calendar-card" class="col">
          <h4>Friday</h4>
          @Html.HiddenFor(m=>m[4].RecipeId)
          <p>@Html.TextBoxFor(m => m[4].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
          <h4 class="day">Saturday</h4>
          @Html.HiddenFor(m=>m[5].RecipeId)
          <p>@Html.TextBoxFor(m => m[5].Title, new { @readonly="readonly" })</p>
      </div>
      <div id="calendar-card" class="col">
        <h4 class="day">Sunday</h4>
        @Html.HiddenFor(m=>m[6].RecipeId)
        <p>@Html.TextBoxFor(m => m[6].Title, new { @readonly="readonly" })</p>
      </div>
    </div>
      <div class="row">
        <div id="calendar-card" class ="col">
          <input type="submit" class="submit" value="Save Meal Plan"><br>
          <div onClick="window.location.reload();" class="clickable">Reshuffle</div> 
        </div>
    </div>
  }
  </div>
}

WhatsForDinner/Views/Calendars/Delete.cshtml
@{
  Layout = "_Layout";
}

@model WhatsForDinner.Models.RecipeWeek

<h2>Are you sure you want to delete this Meal Plan?</h2>

<h4>Week of: @Model.WeekOf.ToShortDateString()</h4>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="submit"/>
}
@Html.ActionLink("Back to List", "Index")